services:
  task-scheduler-service-node-1:
    build:
      context: distributed-task-service/
      dockerfile: Dockerfile
    image: task-scheduler-service:latest
    container_name: task-scheduler-service-node-1
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      EUREKA_URI: http://eureka-server:8761/eureka
      NODE_ID: 1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - eureka-server
  task-scheduler-service-node-2:
    image: task-scheduler-service:latest
    container_name: task-scheduler-service-node-2
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      EUREKA_URI: http://eureka-server:8761/eureka
      NODE_ID: 2
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
      - task-scheduler-service-node-1
      - eureka-server

  task-scheduler-service-node-3:
    image: task-scheduler-service:latest
    container_name: task-scheduler-service-node-3
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      EUREKA_URI: http://eureka-server:8761/eureka
      NODE_ID: 3
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - redis
      - task-scheduler-service-node-1
      - eureka-server
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  eureka-server:
    build:
      context: eureka-discovery-server/
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

volumes:
  pg-data:

networks:
  default:
    name: task_scheduler_network