spring:
  application:
    name: distributed-task-scheduler

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
management:
  health:
    db:
      enabled: true
    redis:
      enabled: true

scheduler:
  poll-interval-ms: 5000
  jitter-ms: 2000
  dispatch-interval-ms: 5000ms
  batch-size: 10