spring:
  application:
    name: eureka-discovery-server


eureka:
  instance:
    lease-expiration-duration-in-seconds: 20
  client:
    register-with-eureka: false
    fetch-registry: false


server.port: 8761
